### Cadastrar um novo MeioPgto
POST https://localhost:5001/api/meiopgto/create
Content-Type: application/json

{
    "Descricao" : "Cartao"
}

### Listar todos os MeioPgtos
GET https://localhost:5001/api/meiopgto/list